### ISSUE TITLE
`Error: Missing root workspace manifest.` during splicing

### ISSUE THREAD

**Issue by criemen** [bazelbuild/rules_rust#2462] opened 2024-02-05 10:30 UTC
TL;DR: repinning the bazel lockfile for a crate universe fails in https://github.com/criemen/rules_rust_repro_splicing

I have a project setup that looks like this:
```
/main:
 Cargo.toml
 Cargo.lock
 src/main.rs
/main/sub:
 Cargo.toml
 src/lib.rs
```
and in `main`'s `Cargo.toml`, I have a dependency of the form `sub = { path = "sub" }`.
That works fine for `cargo build`, but when importing the main's project `Cargo.toml`/`Cargo.lock` with `crates_repository`, and re-pinning the dependencies, I get
```
 ✘ criemen@Corneliuss-MBP  ~/repos/rules_rust_repro_splicing   main  CARGO_BAZEL_REPIN=true bazelisk build //:main
INFO: Repository crate_index instantiated at:
  /Users/criemen/repos/rules_rust_repro_splicing/WORKSPACE.bazel:19:18: in <toplevel>
Repository rule crates_repository defined at:
  /private/var/tmp/_bazel_criemen/032cc9bae4318d18f37d32fd89d111b4/external/rules_rust/crate_universe/private/crates_repository.bzl:107:36: in <toplevel>
INFO: repository @crate_index' used the following cache hits instead of downloading the corresponding file.
 * Hash '7b46480d71c4c34d278c8ce44fbe638ee8e926879de7f47d36ce261c1b9efe91' for https://github.com/bazelbuild/rules_rust/releases/download/0.38.0/cargo-bazel-aarch64-apple-darwin
If the definition of 'repository @crate_index' was updated, verify that the hashes were also updated.
ERROR: An error occurred during the fetch of repository 'crate_index':
   Traceback (most recent call last):
        File "/private/var/tmp/_bazel_criemen/032cc9bae4318d18f37d32fd89d111b4/external/rules_rust/crate_universe/private/crates_repository.bzl", line 59, column 50, in _crates_repository_impl
                metadata_path = splice_workspace_manifest(
        File "/private/var/tmp/_bazel_criemen/032cc9bae4318d18f37d32fd89d111b4/external/rules_rust/crate_universe/private/splicing_utils.bzl", line 178, column 12, in splice_workspace_manifest
                execute(
        File "/private/var/tmp/_bazel_criemen/032cc9bae4318d18f37d32fd89d111b4/external/rules_rust/crate_universe/private/common_utils.bzl", line 54, column 13, in execute
                fail(_EXECUTE_ERROR_MESSAGE.format(
Error in fail: Command [/private/var/tmp/_bazel_criemen/032cc9bae4318d18f37d32fd89d111b4/external/crate_index/cargo-bazel, "splice", "--output-dir", /private/var/tmp/_bazel_criemen/032cc9bae4318d18f37d32fd89d111b4/external/crate_index/splicing-output, "--splicing-manifest", /private/var/tmp/_bazel_criemen/032cc9bae4318d18f37d32fd89d111b4/external/crate_index/splicing_manifest.json, "--config", /private/var/tmp/_bazel_criemen/032cc9bae4318d18f37d32fd89d111b4/external/crate_index/cargo-bazel.json, "--cargo", /private/var/tmp/_bazel_criemen/032cc9bae4318d18f37d32fd89d111b4/external/rust_darwin_aarch64__aarch64-apple-darwin__stable_tools/bin/cargo, "--rustc", /private/var/tmp/_bazel_criemen/032cc9bae4318d18f37d32fd89d111b4/external/rust_darwin_aarch64__aarch64-apple-darwin__stable_tools/bin/rustc, "--cargo-lockfile", /Users/criemen/repos/rules_rust_repro_splicing/Cargo.lock] failed with exit code 1.
STDOUT ------------------------------------------------------------------------

STDERR ------------------------------------------------------------------------
Error: Missing root workspace manifest. Please add the following label to the `manifests` key: "//:Cargo.toml"

ERROR: /Users/criemen/repos/rules_rust_repro_splicing/WORKSPACE.bazel:19:18: fetching crates_repository rule //external:crate_index: Traceback (most recent call last):
        File "/private/var/tmp/_bazel_criemen/032cc9bae4318d18f37d32fd89d111b4/external/rules_rust/crate_universe/private/crates_repository.bzl", line 59, column 50, in _crates_repository_impl
                metadata_path = splice_workspace_manifest(
        File "/private/var/tmp/_bazel_criemen/032cc9bae4318d18f37d32fd89d111b4/external/rules_rust/crate_universe/private/splicing_utils.bzl", line 178, column 12, in splice_workspace_manifest
                execute(
        File "/private/var/tmp/_bazel_criemen/032cc9bae4318d18f37d32fd89d111b4/external/rules_rust/crate_universe/private/common_utils.bzl", line 54, column 13, in execute
                fail(_EXECUTE_ERROR_MESSAGE.format(
Error in fail: Command [/private/var/tmp/_bazel_criemen/032cc9bae4318d18f37d32fd89d111b4/external/crate_index/cargo-bazel, "splice", "--output-dir", /private/var/tmp/_bazel_criemen/032cc9bae4318d18f37d32fd89d111b4/external/crate_index/splicing-output, "--splicing-manifest", /private/var/tmp/_bazel_criemen/032cc9bae4318d18f37d32fd89d111b4/external/crate_index/splicing_manifest.json, "--config", /private/var/tmp/_bazel_criemen/032cc9bae4318d18f37d32fd89d111b4/external/crate_index/cargo-bazel.json, "--cargo", /private/var/tmp/_bazel_criemen/032cc9bae4318d18f37d32fd89d111b4/external/rust_darwin_aarch64__aarch64-apple-darwin__stable_tools/bin/cargo, "--rustc", /private/var/tmp/_bazel_criemen/032cc9bae4318d18f37d32fd89d111b4/external/rust_darwin_aarch64__aarch64-apple-darwin__stable_tools/bin/rustc, "--cargo-lockfile", /Users/criemen/repos/rules_rust_repro_splicing/Cargo.lock] failed with exit code 1.
STDOUT ------------------------------------------------------------------------

STDERR ------------------------------------------------------------------------
Error: Missing root workspace manifest. Please add the following label to the `manifests` key: "//:Cargo.toml"

ERROR: Error computing the main repository mapping: no such package '@crate_index//': Command [/private/var/tmp/_bazel_criemen/032cc9bae4318d18f37d32fd89d111b4/external/crate_index/cargo-bazel, "splice", "--output-dir", /private/var/tmp/_bazel_criemen/032cc9bae4318d18f37d32fd89d111b4/external/crate_index/splicing-output, "--splicing-manifest", /private/var/tmp/_bazel_criemen/032cc9bae4318d18f37d32fd89d111b4/external/crate_index/splicing_manifest.json, "--config", /private/var/tmp/_bazel_criemen/032cc9bae4318d18f37d32fd89d111b4/external/crate_index/cargo-bazel.json, "--cargo", /private/var/tmp/_bazel_criemen/032cc9bae4318d18f37d32fd89d111b4/external/rust_darwin_aarch64__aarch64-apple-darwin__stable_tools/bin/cargo, "--rustc", /private/var/tmp/_bazel_criemen/032cc9bae4318d18f37d32fd89d111b4/external/rust_darwin_aarch64__aarch64-apple-darwin__stable_tools/bin/rustc, "--cargo-lockfile", /Users/criemen/repos/rules_rust_repro_splicing/Cargo.lock] failed with exit code 1.
STDOUT ------------------------------------------------------------------------

STDERR ------------------------------------------------------------------------
Error: Missing root workspace manifest. Please add the following label to the `manifests` key: "//:Cargo.toml"
```

i.e. the main error being 
```
Error: Missing root workspace manifest. Please add the following label to the `manifests` key: "//:Cargo.toml"
```

However, in `WORKSPACE.bazel`, I have
```
crates_repository(
    name = "crate_index",
    cargo_lockfile = "//:Cargo.lock",
    lockfile = "//:Cargo.Bazel.lock",
    manifests = ["//:Cargo.toml"],
)
```

so that manifest key is there.
Can you help me?

**Comment by scentini** [comment] 2024-02-12 10:40
Closing this issue, as it seems like it is not a bug. Feel free to send us a PR to expand on the error message.

**Closed by scentini** 2024-02-12 10:40 UTC
