### ISSUE TITLE
How to set CARGO_PKG_REPOSITORY to make Autometrics compile with rules_rust?

### ISSUE THREAD

**Issue by marvin-hansen** [bazelbuild/rules_rust#2770] opened 2024-07-30 10:06 UTC
Currently, when adding the Autometric crate, the build breaks because CARGO_PKG_REPOSITORY is not set:

```rust
error: environment variable `CARGO_PKG_REPOSITORY` not defined at compile time
   --> external/rules_rust~~crate~crates__autometrics-2.0.0/src/settings.rs:204:32
    |
204 |             .unwrap_or_else(|| env!("CARGO_PKG_REPOSITORY").to_string());
    |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

This is a known issue, already reported a while ago in #70,  but somehow not all Cargo env variables are supported, and it's really clear that the  CARGO_PKG_REPOSITORY env variable needs to be set because the autometric crate expects it during init. The autometric setup file in question:

https://github.com/autometrics-dev/autometrics-rs/blob/9bc24e0935103c990ff5a963079c5db6c4a4792f/autometrics/src/settings.rs#L201

A similar situation was discussed in #2677 , and I actually tried the suggested solution of setting [rustc_env](https://bazelbuild.github.io/rules_rust/defs.html#rust_binary-rustc_env) on the binary target, but this does not work and the build still fails with the same error.  

Also, the[ official Cargo book indicates](https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-crates) that CARGO_PKG_REPOSITORY is expected to be there. I suspect Cargo [ parses the repo URL from the crate cargo.toml](https://github.com/autometrics-dev/autometrics-rs/blob/main/Cargo.toml) and then exposes it as a variable. God only knows why anyone thinks that would be a good idea, but apparently crate authors out there using it, therefore a practical solution would be appreciated. 

Any ideas how to set the CARGO_PKG_REPOSITORY variable to make the Autometrics crate compile?

**Comment by illicitonion** [comment] 2024-08-01 16:14
Closing as a duplicate of https://github.com/bazelbuild/rules_rust/issues/2677

**Closed by illicitonion** 2024-08-01 16:14 UTC
