### ISSUE TITLE
libssh2 generated BUILD file missing openssl-sys deps

### ISSUE THREAD

**Issue by Kila2** [bazelbuild/rules_rust#1928] opened 2023-04-20 14:07 UTC
```
# THIS FILE IS AUTOMATICALLY GENERATED BY CARGO
#
# When uploading crates to the registry Cargo will automatically
# "normalize" Cargo.toml files for maximal compatibility
# with all versions of Cargo and also rewrite `path` dependencies
# to registry (e.g., crates.io) dependencies
#
# If you believe there's an error in this file please file an
# issue against the rust-lang/cargo repository. If you're
# editing this file be aware that the upstream Cargo.toml
# will likely look very different (and much more reasonable)

[package]
name = "libssh2-sys"
version = "0.2.23"
authors = ["Alex Crichton <alex@alexcrichton.com>", "Wez Furlong <wez@wezfurlong.org>", "Matteo Bigoi <bigo@crisidev.org>"]
build = "build.rs"
links = "ssh2"
description = "Native bindings to the libssh2 library"
documentation = "https://docs.rs/libssh2-sys"
license = "MIT/Apache-2.0"
repository = "https://github.com/alexcrichton/ssh2-rs"

[lib]
name = "libssh2_sys"
path = "lib.rs"
[dependencies.libc]
version = "0.2"

[dependencies.libz-sys]
version = "1.1.0"
features = ["libc"]
default-features = false
[build-dependencies.cc]
version = "1.0.25"

[build-dependencies.pkg-config]
version = "0.3.11"

[features]
openssl-on-win32 = ["openssl-sys"]
vendored-openssl = ["openssl-sys/vendored"]
zlib-ng-compat = ["libz-sys/zlib-ng"]
[target."cfg(target_env = \"msvc\")".build-dependencies.vcpkg]
version = "0.2"
[target."cfg(unix)".dependencies.openssl-sys]
version = "0.9.35"
[target."cfg(windows)".dependencies.openssl-sys]
version = "0.9.35"
optional = true
```
```
###############################################################################
# @generated
# DO NOT MODIFY: This file is auto-generated by a crate_universe tool. To 
# regenerate this file, run the following:
#
#     bazel sync --only=crate_index
###############################################################################

load("@rules_rust//cargo:defs.bzl", "cargo_build_script")

load("@rules_rust//rust:defs.bzl", "rust_library")

# buildifier: disable=bzl-visibility
load("@rules_rust//crate_universe/private:selects.bzl", "selects")

package(default_visibility = ["//visibility:public"])

# licenses([
#     "TODO",  # MIT/Apache-2.0
# ])

rust_library(
    name = "libssh2_sys",
    deps = [
        "@crate_index__libc-0.2.137//:libc",
        "@crate_index__libssh2-sys-0.2.23//:build_script_build",
        "@crate_index__libz-sys-1.1.8//:libz_sys",
    ],
    compile_data = glob(
        include = ["**"],
        exclude = [
            "**/* *",
            "BUILD",
            "BUILD.bazel",
            "WORKSPACE",
            "WORKSPACE.bazel",
        ],
    ),
    crate_root = "lib.rs",
    edition = "2015",
    rustc_flags = ["--cap-lints=allow"],
    srcs = glob(["**/*.rs"]),
    tags = [
        "cargo-bazel",
        "crate-name=libssh2-sys",
        "manual",
        "noclippy",
        "norustfmt",
    ],
    version = "0.2.23",
)

cargo_build_script(
    name = "libssh2-sys_build_script",
    crate_name = "build_script_build",
    crate_root = "build.rs",
    data = glob(
        include = ["**"],
        exclude = [
            "**/* *",
            "BUILD",
            "BUILD.bazel",
            "WORKSPACE",
            "WORKSPACE.bazel",
        ],
    ),
    deps = [
        "@crate_index__cc-1.0.77//:cc",
        "@crate_index__pkg-config-0.3.26//:pkg_config",
    ] + select({
        "@rules_rust//rust/platform:aarch64-pc-windows-msvc": [
            "@crate_index__vcpkg-0.2.15//:vcpkg",  # cfg(target_env = "msvc")
        ],
        "@rules_rust//rust/platform:i686-pc-windows-msvc": [
            "@crate_index__vcpkg-0.2.15//:vcpkg",  # cfg(target_env = "msvc")
        ],
        "@rules_rust//rust/platform:x86_64-pc-windows-msvc": [
            "@crate_index__vcpkg-0.2.15//:vcpkg",  # cfg(target_env = "msvc")
        ],
        "//conditions:default": [],
    }),
    edition = "2015",
    links = "ssh2",
    rustc_flags = [
        "--cap-lints=allow",
    ],
    srcs = glob(["**/*.rs"]),
    tags = [
        "cargo-bazel",
        "crate-name=libssh2-sys",
        "manual",
        "noclippy",
        "norustfmt",
    ],
    version = "0.2.23",
    visibility = ["//visibility:private"],
)

alias(
    name = "build_script_build",
    actual = "libssh2-sys_build_script",
    tags = ["manual"],
)
```

**Comment by hobofan** [comment] 2023-04-21 07:05
I think to help you we would also need to see how you invoke `crate_universe` in your `WORKSPACE`.

From what I can deduce from the output here, everything seems roughly in order:
- as there are only windows platforms mentioned in the output, you are probably specifying somewhere that you are only targeting windows
- In the `Cargo.toml`, `openssl-sys` is only only an optional dependency on windows (the `target."cfg(windows)".dependencies.openssl-sys` block)
- To trigger the optional dependency on windows, you would either need to specify the `openssl-on-win32` or `vendored-openssl` feature flags; Depending on what you usage looks like there are different ways on how that can be achieved (e.g. https://bazelbuild.github.io/rules_rust/crate_universe.html#crateannotation )

**Comment by Kila2** [comment] 2023-04-21 07:27
> I think to help you we would also need to see how you invoke `crate_universe` in your `WORKSPACE`.
> 
> From what I can deduce from the output here, everything seems roughly in order:
> 
> * as there are only windows platforms mentioned in the output, you are probably specifying somewhere that you are only targeting windows
> * In the `Cargo.toml`, `openssl-sys` is only only an optional dependency on windows (the `target."cfg(windows)".dependencies.openssl-sys` block)
> * To trigger the optional dependency on windows, you would either need to specify the `openssl-on-win32` or `vendored-openssl` feature flags; Depending on what you usage looks like there are different ways on how that can be achieved (e.g. https://bazelbuild.github.io/rules_rust/crate_universe.html#crateannotation )

My compile env is x86_64-apple-darwin. I'm try to set WORKSPACE
```
crates_repository(
    ...
    annotations = {
        "libssh2-sys": [crate.annotation(
            crate_features = ["vendored-openssl"],
        )],
    },
    supported_platform_triples = [
        "x86_64-apple-darwin"
    ],
    ...
)
```
set libssh2-sys crate_features value to vendored-openssl will get another openssl-src error.
libssh2-sys is an implicit dependency that does not appear in the Cargo.toml file.
There is a Cargo.toml example. Do I still need to set the "libssh2-sys" feature and all implicit dependency features?
```Cargo.toml 
[dependencies]
openssl = { version = "0.10", features = ["vendored"] }
```

**Comment by Gerard19742608jourdain** [comment] 2023-04-24 21:44
Bltoucoin

**Comment by UebelAndre** [comment] 2023-04-24 22:36
Does this happen on 0.21.1?

**Comment by Kila2** [comment] 2023-04-25 05:09
> Does this happen on 0.21.1?

The 0.21.1 generate BUILD.bazel looks good. This issue can be closed.
However, my project still cannot build successfully regarding the inherit ".depenv". I will open a new ticket about it.
```
###############################################################################
# @generated
# DO NOT MODIFY: This file is auto-generated by a crate_universe tool. To 
# regenerate this file, run the following:
#
#     bazel sync --only=crate_index
###############################################################################

load("@rules_rust//cargo:defs.bzl", "cargo_build_script")

load("@rules_rust//rust:defs.bzl", "rust_library")

# buildifier: disable=bzl-visibility
load("@rules_rust//crate_universe/private:selects.bzl", "selects")

package(default_visibility = ["//visibility:public"])

# licenses([
#     "TODO",  # MIT/Apache-2.0
# ])

rust_library(
    name = "libssh2_sys",
    deps = [
        "@crate_index__libc-0.2.137//:libc",
        "@crate_index__libssh2-sys-0.2.23//:build_script_build",
        "@crate_index__libz-sys-1.1.8//:libz_sys",
    ] + select({
        "@rules_rust//rust/platform:x86_64-apple-darwin": [
            "@crate_index__openssl-sys-0.9.78//:openssl_sys",  # cfg(unix)
        ],
        "//conditions:default": [],
    }),
    compile_data = glob(
        include = ["**"],
        exclude = [
            "**/* *",
            "BUILD",
            "BUILD.bazel",
            "WORKSPACE",
            "WORKSPACE.bazel",
        ],
    ),
    crate_root = "lib.rs",
    edition = "2015",
    rustc_flags = ["--cap-lints=allow"],
    srcs = glob(["**/*.rs"]),
    tags = [
        "cargo-bazel",
        "crate-name=libssh2-sys",
        "manual",
        "noclippy",
        "norustfmt",
    ],
    version = "0.2.23",
)

cargo_build_script(
    name = "libssh2-sys_build_script",
    crate_name = "build_script_build",
    crate_root = "build.rs",
    data = glob(
        include = ["**"],
        exclude = [
            "**/* *",
            "BUILD",
            "BUILD.bazel",
            "WORKSPACE",
            "WORKSPACE.bazel",
        ],
    ),
    deps = [
        "@crate_index__cc-1.0.77//:cc",
        "@crate_index__pkg-config-0.3.26//:pkg_config",
    ],
    edition = "2015",
    links = "ssh2",
    rustc_flags = [
        "--cap-lints=allow",
    ],
    srcs = glob(["**/*.rs"]),
    tags = [
        "cargo-bazel",
        "crate-name=libssh2-sys",
        "manual",
        "noclippy",
        "norustfmt",
    ],
    version = "0.2.23",
    visibility = ["//visibility:private"],
)

alias(
    name = "build_script_build",
    actual = "libssh2-sys_build_script",
    tags = ["manual"],
)
```

**Comment by UebelAndre** [comment] 2023-04-25 13:57
if I understand correctly, it looks like the issue is resolved based on
```starlark
rust_library(
    name = "libssh2_sys",
    deps = [
        "@crate_index__libc-0.2.137//:libc",
        "@crate_index__libssh2-sys-0.2.23//:build_script_build",
        "@crate_index__libz-sys-1.1.8//:libz_sys",
    ] + select({
        "@rules_rust//rust/platform:x86_64-apple-darwin": [
            "@crate_index__openssl-sys-0.9.78//:openssl_sys",  # cfg(unix)
        ],
        "//conditions:default": [],
    }),
```
I'm gonna close this issue but if it's actually not fixed, feel free to reopen. For issues building openssl, can you file a new issue?

**Closed by UebelAndre** 2023-04-25 13:57 UTC
Labels: external-crates
