### ISSUE TITLE
Bazel CI: rules_rust is failing on windows in Bazel@HEAD downstream

### ISSUE THREAD

**Issue by SalmaSamy** [bazelbuild/rules_rust#1629] opened 2022-11-04 10:38 UTC
rules_rust is failing in the [downstream](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2719#01843eac-cdcb-4ad0-97a7-732975d4b37a) with the following error:

<img width="1006" alt="Screen Shot 2022-11-03 at 11 08 55 PM" src="https://user-images.githubusercontent.com/16399431/199812532-7c5cbfd2-ac53-4ba3-870b-99dd10698392.png">

/cc @scentini

**Comment by meteorcloudy** [comment] 2022-11-07 10:16
This is also failing with Bazel 5.3.2 after I disabled remote caching for rules_rust, see https://buildkite.com/bazel/rules-rust-rustlang/builds/7338#01845190-54a3-4d53-9c8f-33104a99f6b9

Previously, it was passed because remote caching was used incorrectly, which means your toolchain setup is probably not hermetic.

**Comment by meteorcloudy** [comment] 2022-11-07 10:17
@UebelAndre @hlopko Can you take a look at this issue? This is the only failure in Bazel downstream ;)

**Comment by UebelAndre** [comment] 2022-11-07 19:18
@scentini seems the new opt build introduced by https://github.com/bazelbuild/rules_rust/pull/1621 is failing on windows, would you be able to take a look?

**Comment by meteorcloudy** [comment] 2022-11-09 08:41
Thanks, since the CI is green now, I'll also close this one.

**Comment by meteorcloudy** [comment] 2022-11-09 08:42
But feel free to reopen if you want to use this issue to track follow up fixes ;)

**Comment by scentini** [comment] 2022-11-16 12:45
@meteorcloudy  I have https://github.com/bazelbuild/rules_rust/pull/1658 to reenable the windows job; I believe the issue is that the `--{no}enable_runfiles` flag does not invalidate the action cache. Is this something that should be fixed in Bazel core?

**Closed** 2022-11-16 13:53 UTC
Labels: bug

**Comment by meteorcloudy** [comment] 2022-11-18 15:06
> I believe the issue is that the --{no}enable_runfiles flag does not invalidate the action cache. Is this something that should be fixed in Bazel core?

Ah, this is possible, do you mind filing an issue to bazel repo and perhaps provide a minimal reproduce case? (possibly with disk cache is enough?)
