### ISSUE TITLE
crate_universe: additive_build_file annotations merged into wrong files (stacked)

### ISSUE THREAD

**Issue by uhthomas** [bazelbuild/rules_rust#1277] opened 2022-04-20 15:56 UTC
**rules_rust version:** b778fca0ac4dfcf3c9e24f1517e73d39d739c730

```starlark
load("@rules_rust//crate_universe:defs.bzl", "crate", "crates_repository")

crates_repository(
    name = "crate_index",
    annotations = {
        "rand": [crate.annotation(additive_build_file_content = "# hello rand")],
        "serde": [crate.annotation(additive_build_file_content = "# hello serde")],
    },
    generator = "@cargo_bazel_bootstrap//:cargo-bazel",
    lockfile = "//:Cargo.Bazel.lock",
    packages = {
        "rand": crate.spec(version = "0.8.5"),
        "serde": crate.spec(version = "1.0.136"),
    },
)

load("@crate_index//:defs.bzl", "crate_repositories")

crate_repositories()
```

The resulting [Cargo.Bazel.lock](https://gist.github.com/uhthomas/5f89865499d5b5dea05ec5cbc2fc00cf).

Then, the generated build files:

```
❯ bazel query --output=location @crate_index__rand-0.8.5//...
❯ bazel query --output=location @crate_index__serde-1.0.136//...
```

<img width="871" alt="Screenshot 2022-04-20 at 16 55 33" src="https://user-images.githubusercontent.com/9749173/164272469-faa325e4-f91b-4b43-bee1-f10946c82da0.png">

<img width="897" alt="Screenshot 2022-04-20 at 16 55 54" src="https://user-images.githubusercontent.com/9749173/164272541-d36d8739-0513-4f01-8b18-b5dd54fe9f24.png">

**Comment by uhthomas** [comment] 2022-04-20 16:24
It looks like this is actually included within the lockfile ([here](https://gist.github.com/uhthomas/5f89865499d5b5dea05ec5cbc2fc00cf#file-cargo-bazel-lock-L453)), so it's a bug within the generator.

Likely the starlark repository rule `generate_config`.

https://github.com/bazelbuild/rules_rust/blob/b778fca0ac4dfcf3c9e24f1517e73d39d739c730/crate_universe/private/generate_utils.bzl#L196

**Comment by UebelAndre** [comment] 2022-04-20 16:24
I think the issue is just that `contents` needs to be within the for-loop:
https://github.com/bazelbuild/rules_rust/blob/0.2.1/crate_universe/private/generate_utils.bzl#L208

@uhthomas could I trouble you to give that a try and open a pull-request if that works? 😅 🙏

**Comment by uhthomas** [comment] 2022-04-20 16:27
@UebelAndre Though, what is the behaviour for multiple annotations? Imagine an annotation matching `*` and one matching a specific version. Should the build file content be applied to both, or just one?

**Comment by UebelAndre** [comment] 2022-04-20 16:52
> Ah, great thanks! And finally; it's valid to set both `additive_build_file ` and `additive_build_file_content`. Is this correct?

That's what's expected, yeah. If you don't think that's desirable I'd say file another ticket and we can hash that out. But at the very least the bug you found should be fixed.

**Closed** 2022-04-20 19:55 UTC
Labels: bug, external-crates
