### ISSUE TITLE
no such target '@rust_linux_x86_64//:toolchain_for_x86_64-unknown-linux-gnu_impl'

### ISSUE THREAD

**Issue by kurin** [bazelbuild/rules_rust#382] opened 2020-07-26 20:22 UTC
I'm seeing errors like:

```
ERROR: /[redacted]/BUILD:9:9: Target '//[redacted]' depends on toolchain '@rust_linux_x86_64//:toolchain_for_x86_64-unknown-linux-gnu_impl', which cannot be found: no such target '@rust_linux_x86_64//:toolchain_for_x86_64-unknown-linux-gnu_impl': target 'toolchain_for_x86_64-unknown-linux-gnu_impl' not declared in package '' defined by /[redacted]/33e9ad504fbe8b2bfc8310784ab7e254/external/rust_linux_x86_64/BUILD.bazel'
```

This is when using the `rust_doc` rule.

Near as I can tell, `repositories.bzl` creates two `repository_rule`s, `rust_toolchain_repository` and `rust_toolchain_repository_proxy`, and registers the proxy toolchain.  But apparently `repository_rule`s are only run occasionally, and I'm pretty sure the `rust_toolchain_repository` rule implementation is never actually getting called.

If I look under Bazel's cache I can see `external/rust_linux_x86_64_toolchains/` with the BUILD and WORKSPACE file that the `_proxy` rule creates, but when I look under `external/rust_linux_x86_64`, the BUILD and WORKSPACE files that the non-proxy rule is supposed to create do not exist.

This happens both with the most recent commit at the time of this bug (`8f31b7bc26acdfd11fb046337073840ce50eaeab`) and with the commit from the documentation (`55f77017a7f5b08e525ebeab6e11d8896a4499d2`).

I'm using Bazel 3.3.0:

```
$ bazel --version
bazel 3.3.0-5dd95469d237592d70e55fcc0e029f24bc07516b
```

**Comment by damienmg** [comment] 2020-07-27 08:12
Can you send the part of the WORKSPACE that your are using for including rust dependencies? As well if there is something setting the toolchains in the rust_doc rules, thanks?

If you can do a minimal repro that would be even better ;)

**Comment by kurin** [comment] 2020-07-27 18:14
I don't really know Bazel well enough to get a minimal repro up, sorry.

I'm doing:

```
http_archive(
    name = "io_bazel_rules_rust",
    sha256 = "a0da6d6a7f41bd2bf11ce48b405a18c2128dbf94f6128030faa65891ea725760",
    strip_prefix = "rules_rust-8f31b7bc26acdfd11fb046337073840ce50eaeab",
    urls = [
        "https://github.com/bazelbuild/rules_rust/archive/8f31b7bc26acdfd11fb046337073840ce50eaeab.tar.gz",
    ],
)

load("@io_bazel_rules_rust//rust:repositories.bzl", "rust_repositories")
rust_repositories(version = "1.42.0", edition="2018")
load("@io_bazel_rules_rust//:workspace.bzl", "bazel_version")
bazel_version(name = "bazel_version")
```

**Comment by damienmg** [comment] 2020-07-28 13:47
I could not repro with this simple repository :( :
```
---
BUILD
---
load("@io_bazel_rules_rust//rust:rust.bzl", "rust_library", "rust_doc")

rust_library(name = "mod", srcs = ["mod.rs"])
rust_doc(name = "mod_doc", dep = ":mod")

---
mod.rs
---

// The awesome hello_world
pub fn hello_world() {
  println!("Hello, world!\n");
}


---
WORKSPACE
---
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "io_bazel_rules_rust",
    sha256 = "a0da6d6a7f41bd2bf11ce48b405a18c2128dbf94f6128030faa65891ea725760",
    strip_prefix = "rules_rust-8f31b7bc26acdfd11fb046337073840ce50eaeab",
    urls = [
        "https://github.com/bazelbuild/rules_rust/archive/8f31b7bc26acdfd11fb046337073840ce50eaeab.tar.gz",
    ],
)

http_archive(
    name = "bazel_skylib",
    sha256 = "9a737999532daca978a158f94e77e9af6a6a169709c0cee274f0a4c3359519bd",
    strip_prefix = "bazel-skylib-1.0.0",
    url = "https://github.com/bazelbuild/bazel-skylib/archive/1.0.0.tar.gz",
)

load("@io_bazel_rules_rust//rust:repositories.bzl", "rust_repositories")
rust_repositories(version = "1.42.0", edition="2018")
load("@io_bazel_rules_rust//:workspace.bzl", "bazel_version")
bazel_version(name = "bazel_version")
```

**Comment by kurin** [comment] 2020-07-28 18:34
Well this is new and weird:

```
$ vim BUILD
$ vim mod.rs
$ vim WORKSPACE
$ bazel build mod
Starting local Bazel server and connecting to it...
INFO: SHA256 (https://static.rust-lang.org/dist/rust-std-1.42.0-wasm32-unknown-unknown.tar.gz) = 695439ef4099f2a1da7c9932e556b3985f4ede5b27e6ef260d670bfe4bc3894b
ERROR: /home/kurin/.cache/bazel/_bazel_kurin/4619156b7a153c97eb393eb6e0bbb45b/external/io_bazel_rules_rust/rust/private/rust_tool_wrapper/BUILD:29:1: no such target '@platforms//os:openbsd': target 'openbsd' not declared in package 'os' (did you mean 'freebsd'?) defined by /home/kurin/.cache/bazel/_bazel_kurin/4619156b7a153c97eb393eb6e0bbb45b/external/platforms/os/BUILD and referenced by '@io_bazel_rules_rust//rust/private/rust_tool_wrapper:openbsd'
ERROR: Analysis of target '//:mod' failed; build aborted: Analysis failed
INFO: Elapsed time: 24.660s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (20 packages loaded, 74 targets configured)
```

Sometimes the failure is with "macos" instead.

**Comment by damienmg** [comment] 2020-07-29 08:26
Humm there seems to be related to the platform you are running on, what the full distribution you are using?

**Comment by kurin** [comment] 2020-07-29 19:20
Whoops, I thought I had posted my uname:

```
$ uname -a
Linux kurin-dbx 4.15.0-46-generic #49~16.04.1-Ubuntu SMP Tue Feb 12 17:45:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

I should add that while "macos" doesn't exist in `platforms/os/BUILD`, "osx" does, and that these values come from "https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/util/OS.java", which _does_ have obsd but _doesn't_ have "macos".  (That file also has an entry for "android", which doesn't appear in the github link, so idk what's up with that.)

However, when I muck around with the rust_tool_wrapper/BUILD file to remove references to platforms I don't have, the docs _do_ build.  So there's clearly something wonky going on with my setup.  I'll keep poking around, and I'll update this ticket if I find any news.

**Comment by UebelAndre** [comment] 2023-02-08 08:37
Is this still an issue?

**Comment by kurin** [comment] 2023-02-08 17:15
I don't know if this issue still exists, but I went in a different
direction.

**Comment by UebelAndre** [comment] 2023-02-08 18:12
I'll close this out for now until someone is able to confirm the issue is still occurring on at least `rules_rust v0.17.0`. Sorry for the delay here 😅

**Closed by UebelAndre** 2023-02-08 18:12 UTC
Labels: bug
