### ISSUE TITLE
`CARGO_MANIFEST_DIR was not set` error when building `rust_prost_library`

### ISSUE THREAD

**Issue by nmoroze** [bazelbuild/rules_rust#2669] opened 2024-05-28 15:50 UTC
I'm currently running into an error where building a `rust_prost_library` fails with the following error:

```
thread 'main' panicked at 'CARGO_MANIFEST_DIR was not set: NotPresent', external/rules_rust/cargo/cargo_build_script_runner/bin.rs:33:59
```

I've attached a minimal tarball to reproduce this issue. It sets up `rules_rust` and protobuf tooling per the documentation, and tries to build a simple proto library. I'm not sure if there's something wrong in my setup, or a bug in `rules_rust` - as far as I can tell, this env variable should be set by the `rules_rust` infrastructure.

```shell
$ tar -xzvf reproducer.tar.gz
$ bazel build :foo_lib
...
thread 'main' panicked at 'CARGO_MANIFEST_DIR was not set: NotPresent', external/rules_rust/cargo/cargo_build_script_runner/bin.rs:33:59
...
```

[reproducer.tar.gz](https://github.com/bazelbuild/rules_rust/files/15472608/reproducer.tar.gz)

**Comment by nmoroze** [comment] 2024-06-04 21:09
Following up, it looks like the issue disappears if `.bazelversion` is updated to 7.1.0. I still think this may be a bug, given that `rules_rust` supports Bazel 6.3.0 at a minimum (unless there's some required setup difference between Bazel versions). 

Also note that there's a typo in the reproducer, so it won't quite build cleanly... but the expected result is for it to fail with the error

```
foo.proto:6:13: "FooRequeset" is not defined.
```

**Comment by illicitonion** [comment] 2024-06-06 10:34
I think this is a duplicate of #2665?

**Closed by illicitonion** 2024-06-06 10:34 UTC

**Comment by journaux** [comment] 2024-07-31 15:40
+1
