### ISSUE TITLE
How to add rust repo as external dependency to bazel project

### ISSUE THREAD

**Issue by Quarz0** [bazelbuild/rules_rust#227] opened 2019-05-19 20:40 UTC
I am looking for a way to include [starlark-rust](https://github.com/google/starlark-rust) as an external dependency to my bazel project. I looked into [cargo-raze](https://github.com/google/cargo-raze) but I'm not sure if that's actually what I'm looking for. From what I understood is that cargo-raze would help me generate bazel BUILD files but I couldn't find a way how to use it to include a rust repo as an external dependency, and building the project without having to install cargo or rust.

What I'm looking for is an alternative to [go_repository](https://github.com/bazelbuild/bazel-gazelle/blob/master/repository.rst#go_repository), which I already used and managed to include starlark-go as an external dependency using it.

**Comment by damienmg** [comment] 2019-05-20 08:12
The thing is that go_repository is building go dependencies using Bazel which works well. Cargo integration is subpar at the moment because cargo has concept that Bazel does not have (namely features). Also Bazel does not support recursive 

Cargo-raze itselfs needs Cargo. I had a prototype of something that would not need Cargo once the Cargo.lock file was generated but I never got around to make it usable.

**Comment by UebelAndre** [comment] 2020-07-06 03:36
@damienmg Any updates here?

**Comment by damienmg** [comment] 2020-07-06 09:29
@UebelAndre I was about to restart the work to create a cargo_crate rule, but it will still have to provide the list of features to generate. #2  is indeed a dupe.

**Comment by UebelAndre** [comment] 2020-07-06 15:35
@damienmg Awesome! I'm looking forward to checking it out :D Do you know what issue you're going to be tracking that with? I'd love to follow it.

**Comment by damienmg** [comment] 2020-07-06 15:41
I'll use this issue to track and update #2 when it is merged, there are things related to feature computation that are not feasible at the moment.

**Comment by UebelAndre** [comment] 2020-07-06 15:45
@damienmg Thanks! And just out of curiosity, what are those things?

**Comment by damienmg** [comment] 2020-07-06 16:03
- Feature propagation needs to be able for downstream dependencies to signal upstream dependencies the feature they rely on. This is possible in Bazel thanks to dynamic configuration but last time I checked (the exchange with Marissa on the PR you pinged) there were no timeline on when/if that will be feasible at all from starlark.
- Downloading all dependencies needs to be able to do version resolution and recursive dependency, this is likely never going to be possible.

For the second issue, we could do a rule that basically do a cargo raze and generate the list of dependencies but I'd rather not do it before the first issue is solved.

**Comment by UebelAndre** [comment] 2020-07-09 06:04
@damienmg Do you know if there is an issue tracking the work for the first issue?

**Comment by damienmg** [comment] 2020-07-09 08:06
There is none AFAIR since it is not blocking any work atm I am not interested in pushing this too much. This is however an independent work from this bug.

**Comment by UebelAndre** [comment] 2020-07-10 05:38
I see, so is there a path forward or do you want to wait for the starlark feature?

**Comment by damienmg** [comment] 2020-07-10 08:32
I want to create the rule first, it will ask for the list of feature to declare in the crate, doing the feature propagation is a different story, which is worth solving separately.

I will try to get to the rule work next week, but this is just 20% work for me, so I have other work that take priority?

**Comment by UebelAndre** [comment] 2020-12-02 23:20
Should this be closed in favor of https://github.com/bazelbuild/rules_rust/issues/2 ?

**Comment by damienmg** [comment] 2020-12-03 08:57
Dupe of #2

**Closed by damienmg** 2020-12-03 08:57 UTC
